# Generated by Django 4.1.3 on 2023-01-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='customer',
        ),
    ]
